<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-HCFFR5C" name="TestNGAutomationTesting.TestNG.RegistrationTest" tests="12" failures="1" timestamp="07 May 2020 18:17:02 GMT" time="0.064" errors="0">
  <testcase name="emailTest4" time="0.003" classname="TestNGAutomationTesting.TestNG.RegistrationTest"/>
  <testcase name="emailTest4" time="0.007" classname="TestNGAutomationTesting.TestNG.RegistrationTest"/>
  <testcase name="emailTest3" time="0.001" classname="TestNGAutomationTesting.TestNG.RegistrationTest"/>
  <testcase name="emailTest3" time="0.003" classname="TestNGAutomationTesting.TestNG.RegistrationTest"/>
  <testcase name="phoneTest1" time="0.000" classname="TestNGAutomationTesting.TestNG.RegistrationTest">
    <skipped/>
  </testcase> <!-- phoneTest1 -->
  <testcase name="emailTest2" time="0.002" classname="TestNGAutomationTesting.TestNG.RegistrationTest"/>
  <testcase name="emailTest2" time="0.002" classname="TestNGAutomationTesting.TestNG.RegistrationTest"/>
  <testcase name="phoneTest2" time="0.041" classname="TestNGAutomationTesting.TestNG.RegistrationTest">
    <failure type="java.lang.AssertionError" message="expected [Python] but found [Java]">
      <![CDATA[java.lang.AssertionError: expected [Python] but found [Java]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at TestNGAutomationTesting.TestNG.RegistrationTest.phoneTest2(RegistrationTest.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- phoneTest2 -->
  <testcase name="emailTest1" time="0.002" classname="TestNGAutomationTesting.TestNG.RegistrationTest"/>
  <testcase name="emailTest1" time="0.001" classname="TestNGAutomationTesting.TestNG.RegistrationTest"/>
  <testcase name="phoneTest4" time="0.001" classname="TestNGAutomationTesting.TestNG.RegistrationTest"/>
  <testcase name="phoneTest3" time="0.001" classname="TestNGAutomationTesting.TestNG.RegistrationTest"/>
</testsuite> <!-- TestNGAutomationTesting.TestNG.RegistrationTest -->
